const sections=[
 {id:'opening',roman:'00',title:'Opening — Bauhaus'},
 {id:'understanding',roman:'I',title:'Understanding Bauhaus'},
 {id:'visual-language',roman:'II',title:'The Visual Language'},
 {id:'composition',roman:'2.1',title:'Layout & Composition'},
 {id:'microscope',roman:'III',title:'Works Under the Microscope'},
 {id:'publication',roman:'IV',title:'Bauhaus in Publication'},
 {id:'after',roman:'V',title:'After Bauhaus'}
];
const searchIndex=[
 {section:'understanding',book:'Book I · Bauhaus',title:'Understanding Bauhaus',text:'A school with changing ideas, not a single frozen style.'},
 {section:'visual-language',book:'Book I · Bauhaus',title:'The Visual Language',text:'Layout, typography, image, graphic elements and color.'},
 {section:'composition',book:'Book I · Bauhaus',title:'Asymmetric balance',text:'Follow alignment, scale, counterweight and negative space.'},
 {section:'microscope',book:'Book I · Bauhaus',title:'Joost Schmidt — 1923 exhibition poster',text:'A sourced object and clearly labeled analytical reconstruction.'},
 {section:'publication',book:'Book I · Bauhaus',title:'Bauhaus in Publication',text:'Page systems, sequencing, margins, captions and running matter.'},
 {section:'after',book:'Book I · Bauhaus',title:'After Bauhaus',text:'Historical Bauhaus versus the later visual idea of Bauhaus.'},
 {section:null,book:'Book II · International Typographic Style',title:'Grid systems',text:'Future collection result — content not yet built.'}
];
const state={view:'home',active:'opening',search:false,menu:false};
const getSaved=()=>JSON.parse(localStorage.getItem('tvl-saved')||'[]');
const saveProgress=(id)=>localStorage.setItem('tvl-progress',JSON.stringify({book:'bauhaus',section:id,title:sections.find(s=>s.id===id)?.title||id,at:Date.now()}));
function render(){
 document.querySelector('#app').innerHTML=`${topbar()}${state.view==='home'?home():book()}${state.search?searchPanel():''}`;
 bind(); if(state.view==='book') observe();
}
function topbar(){return `<header class="topbar"><button class="brand" data-home>Three Visual Languages</button><span class="top-spacer"></span><button class="icon-btn hide-mobile" data-search aria-label="Search">Search</button><button class="icon-btn mobile-menu" data-menu aria-label="Toggle contents">☰</button></header>`}
function home(){const p=JSON.parse(localStorage.getItem('tvl-progress')||'null');return `<main class="view home"><div class="home-head"><div><div class="kicker">A digital library · Prototype 01</div><h1>Three visual languages.</h1></div><p class="intro">One quiet reading system. Three books that teach through their own visual construction—without reducing history to a recipe.</p></div>${p?`<div class="resume"><div><span class="label">Continue reading</span><br>Book I · ${p.title}</div><button data-resume="${p.section}">Resume →</button></div>`:'<div style="height:78px"></div>'}<section class="books"><article class="book-card available" data-open-book><span class="status">Prototype available</span><div class="cover-shape"></div><div class="cover-line"></div><h2>Book I<br>Bauhaus</h2><p>How a changing school developed multiple approaches to type, image, form, production, and communication.</p></article><article class="book-card"><span class="status">In research</span><h2>Book II<br>International Typographic Style</h2><p>The title is established. Architecture and content remain intentionally unbuilt.</p></article><article class="book-card"><span class="status">Title provisional</span><h2>Book III<br>Modern Japanese Editorial / Book Design</h2><p>Scope and historically accurate naming require research before design.</p></article></section></main>`}
function sidebar(){return `<aside class="sidebar ${state.menu?'open':''}"><div class="eyebrow">Book I · Reader</div><div class="book-title">Bauhaus</div><nav class="contents">${sections.map(s=>`<button data-jump="${s.id}" class="${state.active===s.id?'active':''}">${s.roman}&nbsp;&nbsp; ${s.title}</button>`).join('')}</nav><div class="sidebar-foot">Prototype content status<br>3 sourced facts · 1 sourced object<br>2 analytical demonstrations<br>Placeholders visibly labeled</div></aside>`}
function book(){let saved=getSaved().includes('bauhaus');return `<main class="view book-layout">${sidebar()}<div class="book-main"><div class="reader-tools"><button data-back title="Return to the location before your last internal jump">← Back</button><button data-save class="${saved?'saved':''}">${saved?'Saved ✓':'Save book'}</button></div><article class="frame">
<section id="opening" class="spread hero" data-loc="Book I · 00"><div class="hero-left"><div><span class="eyebrow">Three visual languages · Book I</span><div class="big-i">I</div></div><h1>bau<br>haus</h1><p class="body-copy">A visual language is not a costume. It is a way of organizing relationships.</p></div><div class="hero-art"><div class="circle"></div><div class="bar"></div><div class="square"></div><div class="vertical">Prototype edition · research in progress</div></div></section>
<section id="understanding" class="spread statement" data-loc="I · 01"><div><span class="evidence-label">Historical fact · sourced</span><h2>A school,<br>not a style.</h2><p class="lead">The graphic language associated with the Bauhaus changed across people, periods, workshops, and purposes.</p></div><div class="fact-card"><p class="body-copy">Early Bauhaus typography included the expressive, calligraphic language associated with Johannes Itten. Later, work by László Moholy-Nagy, Herbert Bayer, and Joost Schmidt helped spread the New Typography. <button class="cite" data-pop="source-archive">1</button></p><p class="body-copy">This book therefore asks <em>how visual relationships work</em>, not how to reproduce a single “Bauhaus look.”</p><button class="term" data-pop="new-typography">What is “New Typography”?</button></div></section>
<section id="visual-language" class="spread visual-language" data-loc="II · 12"><div class="chapter-grid"><div><span class="eyebrow">II · The heaviest section</span><h2 class="chapter-title">The visual language</h2></div><p class="lead">Four lenses for looking. Not four commandments for making.</p></div><div class="lens-list"><div class="lens">Layout & composition</div><div class="lens">Typography</div><div class="lens">Image treatment</div><div class="lens">Graphic elements & color</div></div></section>
<section id="composition" class="spread lab" data-loc="II · 2.1 · 18"><div class="lab-head"><div><span class="evidence-label">Original demonstration · not historical</span><h2>Balance without a center.</h2></div><button class="icon-btn" data-grid>Show analytical grid</button></div><div class="construction"><div class="diagram" id="diagram"><div class="d-type">A</div><div class="d-circle"></div><div class="d-bar"></div></div><div class="measure"><h3>Read the forces</h3><p>This diagram is ours. It demonstrates questions that can be applied to a historical work without claiming one universal construction.</p><div class="measure-row"><span>Dominant mass</span><b>upper right</b></div><div class="measure-row"><span>Counterweight</span><b>lower left</b></div><div class="measure-row"><span>Primary axis</span><b>diagonal</b></div><div class="measure-row"><span>Grid</span><b>8 × 8 overlay</b></div><p><button class="term" data-pop="reconstruction">Why label reconstructions?</button></p></div></div></section>
<section id="microscope" class="spread work" data-loc="III · 34"><div class="work-grid"><figure><div class="object-placeholder"><div class="placeholder-banner">Image placeholder · licensed reproduction required</div><div class="poster-circle"></div><div class="poster-face">A</div><div class="poster-text">bauhaus<br>ausstellung<br>1923</div></div><figcaption class="caption"><strong>Joost Schmidt, <em>Staatliches Bauhaus Ausstellung</em>, 1923</strong>Lithograph, 66.7 × 47.3 cm. Printer: von Reineck & Klein, Weimar. The Museum of Modern Art, gift of Walter Gropius, object 320.1957. <a href="https://www.moma.org/collection/works/6235" target="_blank" rel="noreferrer">Object record ↗</a><br><em>Displayed graphic is a placeholder, not a reproduction.</em></figcaption></figure><div><span class="evidence-label">Sourced object + our analysis</span><h2 style="font-size:clamp(42px,6vw,82px);line-height:.86;margin:14px 0">Under the microscope</h2><p class="body-copy">The object metadata at left is documented by MoMA. The observations below are prompts for a future image-based analysis and must be verified against an authorized reproduction.</p><div class="analysis-points"><div class="point"><b>01</b>Map the dominant circular movement.</div><div class="point"><b>02</b>Test visible alignment axes.</div><div class="point"><b>03</b>Measure scale contrast.</div><div class="point"><b>04</b>Separate observation from intent.</div></div><p style="margin-top:35px"><button class="term" data-pop="citation">Open citation note</button></p></div></div></section>
<section id="publication" class="spread publication" data-loc="IV · 52"><div><span class="eyebrow">IV · Bauhaus in Publication</span><h2 class="chapter-title">A page is part of a sequence.</h2><p class="body-copy">Here the unit of analysis expands: covers, margins, contents, running matter, captions, image rhythm, and the relationship between one page and the next.</p><p class="body-copy"><strong>Prototype note.</strong> The miniature pages are original demonstrations. Later research should replace or pair them with licensed, precisely catalogued pages from Bauhaus publications.</p><button class="term" data-pop="internal" data-internal="composition">See also: composition →</button></div><div class="mini-pages"><div class="mini-page"><div class="rule"></div><div class="textline"></div><div class="textline" style="width:70%"></div><div class="imagebox"></div></div><div class="mini-page"><div class="textline" style="width:40%"></div><div class="textline"></div><div class="textline"></div><div class="textline" style="width:65%"></div><div class="imagebox" style="height:28%;background:var(--yellow)"></div></div></div></section>
<section id="after" class="spread after" data-loc="V · 66"><div><span class="eyebrow">V · After Bauhaus</span><h2>Then<br>≠<br>now</h2></div><div class="after-note"><span class="evidence-label">Critical distinction</span><p class="lead">Historical Bauhaus is not identical to the later visual idea of “Bauhaus.”</p><p class="body-copy">The final section traces transmission and reinvention while keeping later influence visibly separate from work made at the school. This is where the collection can eventually link into Book II without collapsing the two histories.</p><button class="icon-btn" data-home>Return to collection</button></div></section>
</article></div></main>`}
const popovers={
 'source-archive':{title:'[1] Bauhaus.Typography',body:'Bauhaus-Archiv / Museum für Gestaltung. The collection text describes an early expressive-calligraphic phase and the later role of Moholy-Nagy, Bayer, and Schmidt in spreading New Typography.',link:'https://www.bauhaus.de/en/research/publications/bauhaus-typography/'},
 'new-typography':{title:'New Typography',body:'A modernist approach to typographic communication associated with clarity, functional organization, asymmetry, standardized formats, and active relationships among type, image, size, and position. This short definition is provisional; the full chapter will cite primary and scholarly sources.'},
 'reconstruction':{title:'Analytical reconstruction',body:'A diagram we infer from visible evidence. It can reveal alignments and proportions, but it is not proof of the designer’s documented process. Every overlay in the finished book should state which kind it is.'},
 'citation':{title:'Object record',body:'MoMA documents the designer, title, year, medium, dimensions, printer, credit, and object number. A licensed reproduction and page-level visual analysis remain to be completed.',link:'https://www.moma.org/collection/works/6235'},
 'internal':{title:'Internal reference',body:'This link demonstrates a cross-section jump. Your previous location is stored so the Back control returns you to the exact section you came from.'}
};
function searchPanel(){return `<aside class="search-panel"><button class="search-close" data-search>Close ×</button><label class="eyebrow" for="searchInput">Search the collection</label><input id="searchInput" autocomplete="off" placeholder="Try “grid” or “publication”"><div class="search-results" id="results">${results('')}</div></aside>`}
function results(q){let items=searchIndex.filter(x=>(x.title+' '+x.text+' '+x.book).toLowerCase().includes(q.toLowerCase()));return items.map(x=>`<button class="result" ${x.section?`data-result="${x.section}"`:'disabled'}><small>${x.book}</small><br><strong>${x.title}</strong><br>${x.text}</button>`).join('')||'<p>No matching prototype content.</p>'}
function jump(id,remember=true){if(remember&&state.view==='book')sessionStorage.setItem('tvl-back',state.active);state.view='book';state.search=false;state.menu=false;render();requestAnimationFrame(()=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'}));}
function showPop(el,key){document.querySelector('.popover')?.remove();let p=popovers[key],r=el.getBoundingClientRect(),node=document.createElement('div');node.className='popover';node.style.left=Math.min(innerWidth-376,Math.max(16,r.left))+'px';node.style.top=Math.min(innerHeight-210,Math.max(70,r.bottom+10))+'px';node.innerHTML=`<button class="close">×</button><h3>${p.title}</h3><div>${p.body}</div>${p.link?`<p><a href="${p.link}" target="_blank" rel="noreferrer">View source ↗</a></p>`:''}`;document.body.append(node);node.querySelector('.close').onclick=()=>node.remove()}
function bind(){
 document.querySelectorAll('[data-home]').forEach(x=>x.onclick=()=>{state.view='home';state.menu=false;render();scrollTo(0,0)});
 document.querySelectorAll('[data-open-book]').forEach(x=>x.onclick=()=>jump('opening',false));
 document.querySelectorAll('[data-resume]').forEach(x=>x.onclick=()=>jump(x.dataset.resume,false));
 document.querySelectorAll('[data-jump]').forEach(x=>x.onclick=()=>jump(x.dataset.jump));
 document.querySelectorAll('[data-search]').forEach(x=>x.onclick=()=>{state.search=!state.search;render();if(state.search)setTimeout(()=>document.querySelector('#searchInput')?.focus(),0)});
 document.querySelector('[data-menu]')?.addEventListener('click',()=>{state.menu=!state.menu;render()});
 document.querySelector('[data-save]')?.addEventListener('click',()=>{let a=getSaved();a=a.includes('bauhaus')?a.filter(x=>x!=='bauhaus'):[...a,'bauhaus'];localStorage.setItem('tvl-saved',JSON.stringify(a));render()});
 document.querySelector('[data-back]')?.addEventListener('click',()=>jump(sessionStorage.getItem('tvl-back')||'opening',false));
 document.querySelector('[data-grid]')?.addEventListener('click',e=>{document.querySelector('#diagram').classList.toggle('grid-on');e.currentTarget.textContent=document.querySelector('#diagram').classList.contains('grid-on')?'Hide analytical grid':'Show analytical grid'});
 document.querySelectorAll('[data-pop]').forEach(x=>x.onclick=e=>{if(x.dataset.internal)jump(x.dataset.internal);else showPop(x,x.dataset.pop)});
 document.querySelector('#searchInput')?.addEventListener('input',e=>document.querySelector('#results').innerHTML=results(e.target.value));
 document.querySelectorAll('[data-result]').forEach(x=>x.onclick=()=>jump(x.dataset.result));
}
let observer;
function observe(){observer?.disconnect();observer=new IntersectionObserver(es=>{let hit=es.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!hit)return;state.active=hit.target.id;saveProgress(state.active);document.querySelectorAll('[data-jump]').forEach(x=>x.classList.toggle('active',x.dataset.jump===state.active))},{rootMargin:'-20% 0px -55% 0px',threshold:[0,.2,.5]});document.querySelectorAll('.spread').forEach(s=>observer.observe(s))}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&state.search){state.search=false;render()}if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();state.search=true;render();setTimeout(()=>document.querySelector('#searchInput')?.focus(),0)}});
render();

