const sources={
 chronology:{n:1,title:'14 Years of Bauhaus',institution:'Bauhaus-Archiv / Museum für Gestaltung',url:'https://www.bauhaus.de/en/discover/article/14-years-of-bauhaus/'},
 typography:{n:2,title:'Bauhaus.Typography',institution:'Bauhaus-Archiv / Museum für Gestaltung',url:'https://www.bauhaus.de/forschen/publikationen/bauhaus-typography/'},
 bayer:{n:3,title:'Herbert Bayer, Architektur Lichtbilder Vortrag Professor Hans Poelzig',institution:'The Museum of Modern Art',url:'https://www.moma.org/collection/works/5101'},
 schmidt:{n:4,title:'Joost Schmidt, Staatliches Bauhaus Ausstellung',institution:'The Museum of Modern Art',url:'https://www.moma.org/collection/works/6235'},
 books:{n:5,title:'Herbert Bayer, Bauhausbücher 9',institution:'The Museum of Modern Art',url:'https://www.moma.org/collection/works/7355'}
};
const cite=key=>`<button class="cite" data-source="${key}" aria-label="Open source ${sources[key].n}">${sources[key].n}</button>`;
const status=(kind,text)=>`<span class="evidence-status ${kind}">${text}</span>`;
const pages=[
 {id:'opening',folio:'01',chapter:'Book I · Bauhaus',title:'Asymmetry',deck:'Layout & Composition · a seven-page evidence-led study',search:'book chapter opening layout composition asymmetry method',render:()=>`
  <div class="page-running"><span>Three Visual Languages</span><span>Book I</span></div>
  <div class="opening-composition">
    <div class="opening-index"><span>II</span><span>2.1</span></div>
    <div class="opening-title"><p>Layout & Composition</p><h1>Asymmetry</h1></div>
    <div class="opening-deck"><p>A close reading of two Bauhaus-era posters: one documented object, one proposed reconstruction, and a comparison that keeps observation separate from instruction.</p></div>
  </div>
  <div class="page-method">${status('method','Methodology')}<p>Historical facts are sourced. Object metadata comes from collection records. Visual overlays and interpretive claims are explicitly identified as ours.</p></div>
  <p class="geometry-note">Page format: provisional 4:5 digital study, informed by the documented proportions of <em>Bauhausbücher 9</em> but not presented as a historical reconstruction. ${cite('books')}</p>`},
 {id:'context',folio:'02',chapter:'Chapter I · Understanding Bauhaus',title:'Context for this study',deck:'The minimum history needed before reading the posters',search:'understanding bauhaus history 1919 1933 Weimar Dessau context',render:()=>`
  <div class="page-running"><span>Understanding Bauhaus</span><span>Context</span></div>
  <header class="page-header narrow"><span class="section-code">I</span><h1>One school,<br>changing positions.</h1></header>
  <div class="context-layout">
    <div class="context-lead"><p>The Bauhaus existed from 1919 to 1933 and operated in Weimar, Dessau, and Berlin. Its teaching, workshops, personnel, and institutional conditions changed substantially across those fourteen years. ${cite('chronology')}</p></div>
    <div class="context-body"><p>The two posters in this study belong to different moments. Joost Schmidt’s 1923 poster announced the school’s first large public exhibition in Weimar. That year also marked a stronger engagement with industry under Walter Gropius’s formulation “art and technology—a new unity.” ${cite('chronology')}</p><p>Herbert Bayer’s 1926 lecture poster belongs to the Dessau period, after the school established a printing workshop and expanded its publications and public communication. The Bauhaus-Archiv describes the school’s typography as varied rather than singular, moving from early expressive-calligraphic work toward approaches associated with New Typography. ${cite('typography')}</p></div>
  </div>
  <aside class="scope-note">${status('fact','Historical context · sourced')}<p>This page supports the Asymmetry pilot only. It is not a substitute for the eventual, substantially larger Chapter I.</p></aside>`},
 {id:'introduction',folio:'03',chapter:'Layout & Composition',title:'Reading asymmetry',deck:'Begin with the object, not a formula',search:'asymmetry explanation visual weight alignment hierarchy direction',render:()=>`
  <div class="page-running"><span>Layout & Composition</span><span>Asymmetry</span></div>
  <header class="page-header"><span class="section-code">2.1</span><h1>Balance without mirrored halves.</h1></header>
  <div class="intro-layout">
    <div class="intro-prose"><p class="dropcap">Asymmetry describes an unequal distribution of elements around a page. It does not mean the absence of order. A composition may use differences in scale, density, interval, direction, or position to create relationships without bilateral symmetry.</p><p>For this study, Herbert Bayer’s 1926 lecture poster provides unusually firm documentary footing: MoMA describes it as using an underlying grid and an asymmetrical composition. ${cite('bayer')}</p><p>That statement does not reveal Bayer’s exact construction process. We can inspect the work for repeated edges, zones, and directional movement, but any grid we draw remains a proposed analytical reconstruction.</p></div>
    <div class="question-column"><h2>Questions for the object</h2><ol><li>Where does reading begin?</li><li>Which edges repeat?</li><li>How are unequal masses balanced?</li><li>Where does space separate information?</li><li>What directs the eye onward?</li></ol>${status('method','Non-prescriptive study')}<p>These questions organize looking; they are not steps for making a “Bauhaus” composition.</p></div>
  </div>`},
 {id:'bayer-object',folio:'04',chapter:'Historical object',title:'Herbert Bayer',deck:'A lecture poster from the Dessau period',search:'Herbert Bayer Architektur Lichtbilder Hans Poelzig 1926 letterpress MoMA',render:()=>`
  <div class="page-running"><span>Historical object</span><span>MoMA 108.1968</span></div>
  <div class="object-page">
    <figure class="object-figure bayer-ratio"><div class="rights-panel"><span>Artwork reproduction not included</span><strong>48.6 × 65.1 cm</strong><small>View the authorized collection image at MoMA</small><a href="${sources.bayer.url}" target="_blank" rel="noreferrer">Open object record ↗</a></div></figure>
    <div class="object-record">${status('object','Historical object · sourced')}<h1>Herbert Bayer</h1><h2><em>Architektur Lichtbilder Vortrag Professor Hans Poelzig</em></h2><dl><div><dt>Date</dt><dd>1926</dd></div><div><dt>Medium</dt><dd>Letterpress</dd></div><div><dt>Dimensions</dt><dd>48.6 × 65.1 cm</dd></div><div><dt>Printer</dt><dd>Bauhausdruck</dd></div><div><dt>Collection</dt><dd>The Museum of Modern Art</dd></div><div><dt>Credit</dt><dd>Gift of Philip Johnson</dd></div><div><dt>Object</dt><dd>108.1968</dd></div></dl><p class="source-line">Collection record and metadata: MoMA. ${cite('bayer')}</p></div>
  </div>`},
 {id:'bayer-analysis',folio:'05',chapter:'Work under analysis',title:'A proposed reading',deck:'Documented description and analytical reconstruction',search:'Bayer analysis grid axes alignment visual weight hierarchy overlay',render:()=>`
  <div class="page-running"><span>Work under analysis</span><span>Bayer · 1926</span></div>
  <div class="analysis-page">
    <div class="analysis-visual ${state.overlay?'overlay-on':''}">
      <div class="reconstruction"><span class="r-a">ARCHITEKTUR</span><span class="r-b">LICHTBILDER</span><span class="r-c">VORTRAG</span><span class="r-d">information groups</span><i class="axis axis-a"></i><i class="axis axis-b"></i></div>
      <button class="overlay-toggle" data-overlay>${state.overlay?'Hide proposed structure':'Show proposed structure'}</button>
    </div>
    <div class="analysis-copy">${status('analysis','Analytical reconstruction · ours')}<h1>Order is visible.<br>The exact grid is not.</h1><p>MoMA identifies sans-serif type, an underlying grid, uppercase lettering, and asymmetrical composition in the poster. ${cite('bayer')} The reconstruction at left does not reproduce Bayer’s poster and does not claim to recover his working grid.</p><h2>What we are testing</h2><ul><li><b>Alignment:</b> whether separated information groups share visible edges.</li><li><b>Weight:</b> how differences in type scale and density offset one another.</li><li><b>Interval:</b> how open areas distinguish subject, speaker, and event information.</li><li><b>Direction:</b> how changes in orientation and position propose a reading path.</li></ul><p class="analysis-limit">Only relationships verifiable against the collection image should survive into publication.</p></div>
  </div>`},
 {id:'comparison',folio:'06',chapter:'Focused comparison',title:'Two asymmetries',deck:'Different organizations, not one Bauhaus recipe',search:'Joost Schmidt Staatliches Bauhaus Ausstellung 1923 comparison lithograph',render:()=>`
  <div class="page-running"><span>Focused comparison</span><span>1923 / 1926</span></div>
  <header class="comparison-head"><span class="section-code">2.1</span><h1>Asymmetry is not one arrangement.</h1></header>
  <div class="comparison-layout">
    <div class="comparison-object"><div class="mini-object schmidt-ratio"><span>Reproduction<br>not included</span><a href="${sources.schmidt.url}" target="_blank" rel="noreferrer">View at MoMA ↗</a></div><h2>Joost Schmidt</h2><p><em>Staatliches Bauhaus Ausstellung</em>, 1923. Lithograph, 66.7 × 47.3 cm. Printed by von Reineck & Klein, Weimar. MoMA, gift of Walter Gropius. Object 320.1957. ${cite('schmidt')}</p></div>
    <div class="comparison-object"><div class="mini-object bayer-ratio"><span>Reproduction<br>not included</span><a href="${sources.bayer.url}" target="_blank" rel="noreferrer">View at MoMA ↗</a></div><h2>Herbert Bayer</h2><p><em>Architektur Lichtbilder Vortrag Professor Hans Poelzig</em>, 1926. Letterpress, 48.6 × 65.1 cm. Bauhausdruck. MoMA, gift of Philip Johnson. Object 108.1968. ${cite('bayer')}</p></div>
  </div>
  <aside class="comparison-prompt">${status('analysis','Comparison prompts · ours')}<p>Compare orientation, the relationship of type and image, the direction of visual movement, and the distribution of dense and open areas. The purpose is to identify difference—not to extract a shared formula.</p></aside>`},
 {id:'conclusion',folio:'07',chapter:'Conclusion',title:'What the evidence supports',deck:'A bridge to alignment and negative space',search:'conclusion evidence alignment negative space non-prescriptive',render:()=>`
  <div class="page-running"><span>Conclusion</span><span>Asymmetry</span></div>
  <header class="page-header conclusion-head"><span class="section-code">2.1</span><h1>A relationship,<br>not a look.</h1></header>
  <div class="conclusion-layout"><div class="conclusion-main"><p>These works support a limited claim: Bauhaus-era graphic communication could organize unequal elements through deliberate relationships of scale, position, interval, direction, type, and image.</p><p>The Bayer record gives us documentary support for an underlying grid and asymmetrical composition. ${cite('bayer')} The Schmidt record gives us a second documented object from a different Bauhaus moment, but its design intentions and construction process should not be inferred without further evidence. ${cite('schmidt')}</p><p>Asymmetry therefore remains a way to examine how a particular work holds together—not a recipe for reproducing a historical style.</p></div><div class="next-concept"><span>Next concept</span><h2>Alignment</h2><p>How can separated elements become related through a repeated edge or axis?</p><button data-jump="introduction">Revisit the questions ←</button></div></div>
  <div class="closing-status">${status('fact','Facts · sourced')}${status('analysis','Observations · attributed')}${status('method','Application · left to the reader')}</div>`}
];

const state={view:'home',page:0,search:false,menu:false,overlay:false,history:[]};
const saved=()=>JSON.parse(localStorage.getItem('tvl-saved')||'[]');
const progress=()=>{const p=JSON.parse(localStorage.getItem('tvl-progress')||'null');const i=pages.findIndex(x=>x.id===p?.section);return i<0?0:i};
function storeProgress(){const p=pages[state.page];localStorage.setItem('tvl-progress',JSON.stringify({book:'bauhaus',section:p.id,title:p.title,page:state.page+1,at:Date.now()}))}
function render(){document.querySelector('#app').innerHTML=`${topbar()}${state.view==='home'?home():reader()}${state.search?searchPanel():''}`;bind()}
function topbar(){return `<header class="topbar"><button class="brand" data-home>Three Visual Languages</button><span class="top-spacer"></span><span class="edition">Prototype 03 · seven-page study</span><button class="shell-button" data-search>Search <kbd>Ctrl K</kbd></button>${state.view==='book'?'<button class="shell-button mobile-only" data-menu>Pages</button>':''}</header>`}
function home(){const p=JSON.parse(localStorage.getItem('tvl-progress')||'null'),valid=p&&pages.some(x=>x.id===p.section);return `<main class="home"><section class="home-intro"><div><span class="eyebrow">A digital teaching library</span><h1>Three visual languages.</h1></div><div><p>A reader shell containing books as finite editorial objects.</p><p class="muted">Prototype 03 tests one complete seven-page sequence rather than the full Bauhaus content architecture.</p></div></section>${p?`<div class="resume"><div><span>Continue reading</span><strong>Book I · ${valid?p.title:'Asymmetry'}</strong></div><button data-resume="${valid?p.section:'opening'}">Resume page ${valid?p.page||1:1} →</button></div>`:''}<section class="books"><article class="book-card active" data-open-book tabindex="0"><span class="book-no">01</span><span class="book-status">Pilot available</span><h2>Bauhaus</h2><p>Layout & Composition · Asymmetry</p><small>7 finite pages · evidence-led study</small><b>Open book →</b></article><article class="book-card dormant"><span class="book-no">02</span><span class="book-status">In research</span><h2>International Typographic Style</h2></article><article class="book-card dormant"><span class="book-no">03</span><span class="book-status">Scope provisional</span><h2>Modern Japanese Editorial / Book Design</h2></article></section></main>`}
function sidebar(){return `<aside class="sidebar ${state.menu?'open':''}" aria-label="Book pages"><div class="sidebar-head"><span>Book I</span><strong>Bauhaus</strong><small>Layout & Composition · Asymmetry</small></div><nav class="page-outline">${pages.map((p,i)=>`<button data-page="${i}" class="${i===state.page?'active':''}"><span>${String(i+1).padStart(2,'0')}</span><div><b>${p.title}</b><small>${p.chapter}</small></div></button>`).join('')}</nav><div class="sidebar-note">Seven-page pilot<br>Full Book I intentionally deferred</div></aside>`}
function reader(){const p=pages[state.page],isSaved=saved().includes('bauhaus');return `<main class="book-shell">${sidebar()}<section class="reading-area"><div class="reader-tools"><button data-back ${state.history.length?'':'disabled'}>← History</button><span>Page ${state.page+1} of ${pages.length}</span><button data-save class="${isSaved?'saved':''}">${isSaved?'Saved ✓':'Save book'}</button></div><div class="reading-viewport" aria-live="polite"><article class="publication-page page-${p.id}" aria-label="Page ${state.page+1}: ${p.title}">${p.render()}<span class="folio">${p.folio}</span></article></div><nav class="page-controls" aria-label="Page navigation"><button data-prev ${state.page===0?'disabled':''}>← Previous</button><div><b>${p.chapter}</b><span>${p.title}</span></div><button data-next ${state.page===pages.length-1?'disabled':''}>Next →</button></nav></section></main>`}
function goTo(index,{remember=true}={}){if(index<0||index>=pages.length||index===state.page)return;if(remember)state.history.push(state.page);state.page=index;state.menu=false;state.overlay=false;storeProgress();render()}
function goId(id,opts){const i=pages.findIndex(x=>x.id===id);if(i>=0)goTo(i,opts)}
function sourcePopover(el,key){document.querySelector('.popover')?.remove();const s=sources[key],r=el.getBoundingClientRect(),n=document.createElement('aside');n.className='popover';n.style.left=Math.min(innerWidth-390,Math.max(16,r.left))+'px';n.style.top=Math.min(innerHeight-220,Math.max(70,r.bottom+8))+'px';n.innerHTML=`<button class="close" aria-label="Close">×</button><span>Source ${s.n}</span><h3>${s.title}</h3><p>${s.institution}</p><a href="${s.url}" target="_blank" rel="noreferrer">Open authoritative source ↗</a>`;document.body.append(n);n.querySelector('.close').onclick=()=>n.remove()}
function searchPanel(){return `<aside class="search-panel" role="dialog" aria-modal="true"><button class="search-close" data-search>Close ×</button><label for="searchInput">Search this pilot</label><input id="searchInput" autocomplete="off" placeholder="Try “grid” or “Schmidt”"><div id="results">${results('')}</div></aside>`}
function results(q){q=q.toLowerCase();return pages.filter(p=>`${p.title} ${p.deck} ${p.search}`.toLowerCase().includes(q)).map((p)=>{const i=pages.indexOf(p);return `<button class="result" data-result="${i}"><span>Page ${i+1}</span><b>${p.title}</b><small>${p.deck}</small></button>`}).join('')||'<p>No matching page.</p>'}
function bind(){
 document.querySelectorAll('[data-home]').forEach(x=>x.onclick=()=>{state.view='home';state.menu=false;render();scrollTo(0,0)});
 document.querySelectorAll('[data-open-book]').forEach(x=>{x.onclick=()=>{state.view='book';state.page=0;state.history=[];storeProgress();render()};x.onkeydown=e=>{if(['Enter',' '].includes(e.key))x.click()}});
 document.querySelectorAll('[data-resume]').forEach(x=>x.onclick=()=>{state.view='book';state.page=pages.findIndex(p=>p.id===x.dataset.resume);if(state.page<0)state.page=0;render()});
 document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>goTo(Number(x.dataset.page)));
 document.querySelector('[data-prev]')?.addEventListener('click',()=>goTo(state.page-1));document.querySelector('[data-next]')?.addEventListener('click',()=>goTo(state.page+1));
 document.querySelector('[data-back]')?.addEventListener('click',()=>{const previous=state.history.pop();if(previous!==undefined){state.page=previous;state.overlay=false;storeProgress();render()}});
 document.querySelectorAll('[data-jump]').forEach(x=>x.onclick=()=>goId(x.dataset.jump));
 document.querySelector('[data-overlay]')?.addEventListener('click',()=>{state.overlay=!state.overlay;render()});
 document.querySelector('[data-save]')?.addEventListener('click',()=>{let a=saved();a=a.includes('bauhaus')?a.filter(x=>x!=='bauhaus'):[...a,'bauhaus'];localStorage.setItem('tvl-saved',JSON.stringify(a));render()});
 document.querySelectorAll('[data-source]').forEach(x=>x.onclick=()=>sourcePopover(x,x.dataset.source));
 document.querySelectorAll('[data-search]').forEach(x=>x.onclick=()=>{state.search=!state.search;render();if(state.search)setTimeout(()=>document.querySelector('#searchInput')?.focus())});
 document.querySelector('[data-menu]')?.addEventListener('click',()=>{state.menu=!state.menu;render()});
 document.querySelector('#searchInput')?.addEventListener('input',e=>{document.querySelector('#results').innerHTML=results(e.target.value);bindResults()});bindResults();
}
function bindResults(){document.querySelectorAll('[data-result]').forEach(x=>x.onclick=()=>{state.search=false;state.view='book';goTo(Number(x.dataset.result))})}
document.addEventListener('keydown',e=>{const typing=['INPUT','TEXTAREA'].includes(document.activeElement?.tagName);if(e.key==='Escape'){if(state.search){state.search=false;render()}else if(state.menu){state.menu=false;render()}else document.querySelector('.popover')?.remove()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();state.search=true;render();setTimeout(()=>document.querySelector('#searchInput')?.focus())}if(state.view==='book'&&!typing&&!state.search){if(e.key==='ArrowRight'||e.key==='PageDown'){e.preventDefault();goTo(state.page+1)}if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();goTo(state.page-1)}}});
render();
