const outline=[
 ['opening','00','Opening',0,'A changing school, not a frozen style'],['orientation','I','How to read this book',0,'Evidence, observation and analysis'],['visual-language','II','The Visual Language',0,'Four lenses for visual relationships'],
 ['layout-composition','','Layout & Composition',1,'Fields, axes, weight and space'],['grid','','Grid',2,'Regularity, intervals and exceptions'],['alignment','','Alignment',2,'Shared edges and deliberate offsets'],['asymmetry','','Asymmetry',2,'Counterweight, direction and distance'],['negative-space','','Negative Space',2,'Empty area as active interval'],
 ['typography','','Typography',1,'Type as information and structure'],['hierarchy','','Hierarchy',2,'Sequences of attention'],['type-systems','','Type Systems',2,'Stable roles across pages'],['scale-contrast','','Scale & Contrast',2,'Relative size and density'],
 ['image-treatment','','Image Treatment',1,'Photography, crop and sequence'],['photo-type','','Image + Type',2,'Reinforce, interrupt or reframe'],['crop-sequence','','Crop & Sequence',2,'Framing changes evidence'],['caption-evidence','','Caption as Evidence',2,'Metadata separated from analysis'],
 ['graphic-color','','Graphic Elements & Color',1,'Functional relationships, not a formula'],['graphic-elements','','Graphic Elements',2,'Connect, group and locate'],['color-function','','Color Function',2,'Classify, emphasize and connect'],['restraint','','Restraint',2,'Question the primary-color shorthand'],
 ['microscope','III','Works Under the Microscope',0,'Sourced objects and transparent analysis'],['publication','IV','Bauhaus in Publication',0,'Pages as sequences and systems'],['after','V','After Bauhaus',0,'History separated from later reception']
].map(([id,roman,title,level,search])=>({id,roman,title,level,search}));
const state={view:'home',active:'opening',search:false,menu:false};
const section=id=>outline.find(x=>x.id===id),saved=()=>JSON.parse(localStorage.getItem('tvl-saved')||'[]');
const remember=id=>localStorage.setItem('tvl-progress',JSON.stringify({book:'bauhaus',section:id,title:section(id)?.title||id,at:Date.now()}));
const badge=(kind,text)=>`<span class="evidence-label ${kind}">${text}</span>`;
const frame=(id,loc,html,cls='')=>`<section id="${id}" class="page-frame ${cls}" data-loc="${loc}">${html}</section>`;
const head=(n,title,lead)=>`<header class="frame-head"><div><span class="chapter-number">${n}</span><h2>${title}</h2></div><p class="lead">${lead}</p></header>`;

function render(){document.querySelector('#app').innerHTML=`${topbar()}${state.view==='home'?home():book()}${state.search?searchPanel():''}`;bind();if(state.view==='book')observe()}
function topbar(){return `<header class="topbar"><button class="brand" data-home>Three Visual Languages</button><span class="top-spacer"></span><span class="edition hide-mobile">Prototype 02 · editorial study</span><button class="text-button hide-mobile" data-search>Search <kbd>Ctrl K</kbd></button>${state.view==='book'?'<button class="text-button mobile-menu" data-menu>Contents</button>':''}</header>`}
function home(){const stored=JSON.parse(localStorage.getItem('tvl-progress')||'null'),p=stored&&section(stored.section)?stored:stored?{section:'orientation',title:'How to read this book'}:null;return `<main class="home"><section class="home-intro"><div><div class="kicker">A digital teaching library · Prototype 02</div><h1>Three visual languages.</h1></div><div><p class="intro">A reading system for learning how visual relationships work through evidence, comparison, and close looking.</p><p>The architecture is under test. Its appearance stays deliberately neutral while research continues.</p></div></section>${p?`<div class="resume"><div><span class="label">Continue reading</span><strong>Book I · ${p.title}</strong></div><button class="action" data-resume="${p.section}">Resume →</button></div>`:''}<section class="books"><article class="book-card available" data-open-book tabindex="0"><b class="book-index">01</b><span class="status">Prototype available</span><h2>Book I<br>Bauhaus</h2><p>A study of changing approaches to type, image, form, production, and communication.</p><span>Open book →</span></article><article class="book-card muted"><b class="book-index">02</b><span class="status">In research</span><h2>International Typographic Style</h2><p>Architecture and content remain intentionally unbuilt.</p></article><article class="book-card muted"><b class="book-index">03</b><span class="status">Scope provisional</span><h2>Modern Japanese Editorial / Book Design</h2><p>Historically accurate scope and naming require research.</p></article></section></main>`}
function sidebar(){return `<aside class="sidebar ${state.menu?'open':''}"><div class="sidebar-head"><span>Book I · Reader</span><strong>Bauhaus</strong></div><nav class="contents">${outline.map(x=>`<button data-jump="${x.id}" data-level="${x.level}" class="${state.active===x.id?'active':''}">${x.roman?`<i>${x.roman}</i>`:''}<span>${x.title}</span></button>`).join('')}</nav><div class="sidebar-foot">Evidence-led prototype<br>Reproductions pending rights review</div></aside>`}
function book(){const isSaved=saved().includes('bauhaus');return `<main class="book-layout">${sidebar()}<div class="book-main"><div class="reader-tools"><button data-back>← Back</button><span id="location">Book I · 00</span><button data-save class="${isSaved?'saved':''}">${isSaved?'Saved ✓':'Save book'}</button></div><article class="reader">${opening()}${visualLanguage()}${objects()}${ending()}</article></div></main>`}

function opening(){return frame('opening','Book I · 00',`<div class="title-grid"><div><span class="eyebrow">Three Visual Languages · Book I</span><h1>Bauhaus</h1></div><div><p class="lead">A school with changing ideas—not a frozen visual style.</p><p>This book studies relationships among type, image, space, production, and communication. It does not offer a recipe for making work “look Bauhaus.”</p></div></div><div class="scope-line"><span>1919–1933</span><span>Weimar · Dessau · Berlin</span><span>Research in progress</span></div>`,'opening-frame')+frame('orientation','I · How to read this book',head('I','How to read this book','Look first. Name the evidence. Then test an interpretation.')+`<div class="module-grid four-up">${[['01','Observe','Describe visible relationships without assigning intent.'],['02','Locate','Identify creator, date, medium, purpose, and source.'],['03','Analyze','Measure alignments, intervals, hierarchy, and sequence.'],['04','Distinguish','Keep documented process separate from inference.']].map(x=>`<article class="module"><span>${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('')}</div><div class="evidence-key">${badge('fact','Historical fact · sourced')}${badge('demo','Original demonstration · not historical')}${badge('object','Sourced object + our analysis')}${badge('reconstruction','Analytical reconstruction')}</div>`)}

function visualLanguage(){return frame('visual-language','II · The Visual Language',head('II','The Visual Language','Four connected lenses for close reading. Each breaks into questions that can be tested against real work.')+`<div class="lens-index">${[['2.1','layout-composition','Layout & Composition','fields · axes · weight · space'],['2.2','typography','Typography','hierarchy · roles · contrast'],['2.3','image-treatment','Image Treatment','relation · crop · sequence'],['2.4','graphic-color','Graphic Elements & Color','direction · classification · restraint']].map(x=>`<button data-jump="${x[1]}"><b>${x[0]}</b><span>${x[2]}</span><small>${x[3]}</small></button>`).join('')}</div>`,'chapter-opening')+
 frame('layout-composition','II · 2.1 · Layout & Composition',head('2.1','Layout & Composition','A page is a field of forces. Parts gain meaning through position, interval, scale, and relation.'))+
 frame('grid','II · 2.1.1 · Grid',`<div class="topic-layout"><div>${badge('reconstruction','Analytical reconstruction')}<h2>Grid</h2><p class="lead">A grid is one possible account of visible regularity—not proof of a designer’s process.</p><p>Begin with repeated edges and intervals. Propose the smallest structure that explains them, then record the exceptions.</p><button class="term" data-pop="reconstruction">Why label reconstructions?</button></div><div class="lab-panel"><div class="diagram" id="diagram"><strong>VISIBLE<br>RELATIONS</strong><small>edge / interval / exception</small></div><div>${badge('demo','Original demonstration · not historical')}<button class="action" data-grid>Show analytical grid</button></div></div></div>`)+
 lesson('alignment','II · 2.1.2 · Alignment','2.1.2','Alignment','An edge can connect information that never touches.',`<div class="module-grid three-up"><article class="module"><div class="edge-demo shared"></div><h3>Shared edge</h3><p>Separate elements group when their beginnings repeat.</p></article><article class="module"><div class="edge-demo offset"></div><h3>Deliberate offset</h3><p>A broken edge can create hierarchy or signal a new role.</p></article>${promptBox(['Trace the strongest edges.','Note which elements comply.','Ask what each exception accomplishes.'])}</div>`)+
 lesson('asymmetry','II · 2.1.3 · Asymmetry','2.1.3','Asymmetry','Balance can emerge from unequal forms through weight, direction, and distance.',`<div class="comparison"><div class="asym-demo"><b>Large mass</b><small>small / distant counterweight</small></div><div><h3>Measure relationships</h3><dl><div><dt>Mass</dt><dd>size × density</dd></div><div><dt>Distance</dt><dd>from the visual center</dd></div><div><dt>Direction</dt><dd>where edges pull</dd></div></dl><p class="note">A lens for description, not a formula.</p></div></div>`)+
 lesson('negative-space','II · 2.1.4 · Negative Space','2.1.4','Negative Space','Empty area separates, groups, delays, and emphasizes.',`<div class="space-study"><div class="space-field"><span>A</span><span>B</span></div><div class="annotation"><h3>Look between</h3><p>Compare intervals within a group to those between groups. Their difference often carries more structure than a border.</p></div></div>`)+
 frame('typography','II · 2.2 · Typography',head('2.2','Typography','Type communicates through language and visible organization; Bauhaus typography varied across periods, people, and purposes.')+`<div class="source-note">${badge('fact','Historical fact · sourced')}<p>The Bauhaus-Archiv describes an early expressive-calligraphic phase and later work associated with Moholy-Nagy, Bayer, and Schmidt that helped spread New Typography. <button class="cite" data-pop="source-archive">1</button></p></div>`)+
 lesson('hierarchy','II · 2.2.1 · Hierarchy','2.2.1','Hierarchy','Hierarchy is a proposed reading sequence, not a list of font sizes.',`<div class="hierarchy-study"><div class="type-specimen"><strong>lecture</strong><span>architecture · light images</span><small>professor hans poelzig / 1926</small></div>${promptBox(['What enters first?','What clarifies the subject?','What supplies logistical detail?'])}</div>`)+
 lesson('type-systems','II · 2.2.2 · Type Systems','2.2.2','Type Systems','A system assigns stable roles while allowing each page to respond.',`<div class="role-table"><b>Role</b><b>Job</b><b>Variable</b><span>Chapter</span><span>orient</span><span>scale / position</span><span>Topic</span><span>locate</span><span>weight / spacing</span><span>Caption</span><span>document</span><span>density / measure</span><span>Annotation</span><span>interpret</span><span>rule / offset</span></div>`)+
 lesson('scale-contrast','II · 2.2.3 · Scale & Contrast','2.2.3','Scale & Contrast','Contrast makes difference legible; repetition makes it meaningful.',`<div class="module-grid two-up"><article class="module"><div class="scale-demo">A <small>a</small></div><h3>Relative scale</h3><p>Measure one element against its neighbors.</p></article><article class="module"><div class="density-demo">|||| | |</div><h3>Density</h3><p>Compressed and open regions establish pace.</p></article></div>`)+
 frame('image-treatment','II · 2.3 · Image Treatment',head('2.3','Image Treatment','An image is selected, framed, scaled, sequenced, and captioned. Each operation changes meaning.'))+
 lesson('photo-type','II · 2.3.1 · Image + Type','2.3.1','Image + Type','Image and language may identify, reinforce, interrupt, or reframe one another.',`<div class="image-type-study"><div class="image-placeholder"><span>IMAGE STUDY</span><small>Original demonstration</small></div><div><strong>One image,<br>three relations</strong><ol><li>Caption identifies.</li><li>Headline frames.</li><li>Annotation directs attention.</li></ol></div></div>`)+
 lesson('crop-sequence','II · 2.3.2 · Crop & Sequence','2.3.2','Crop & Sequence','Cropping argues about relevance. Sequence turns frames into comparison.',`<div class="crop-strip">${['context','relation','detail'].map((x,i)=>`<figure><div class="crop crop-${i}"></div><figcaption>0${i+1} · ${x}</figcaption></figure>`).join('')}</div><p class="note">The same neutral study is reframed as context narrows.</p>`)+
 lesson('caption-evidence','II · 2.3.3 · Caption as Evidence','2.3.3','Caption as Evidence','Let readers separate the object record from interpretation.',`<div class="caption-anatomy">${[['Creator','who made it'],['Title · year','what and when'],['Medium / publication','material context'],['Institution · object no.','verifiable source'],['Analysis label','whose claim this is']].map(x=>`<div><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}</div>`)+
 frame('graphic-color','II · 2.4 · Graphic Elements & Color',head('2.4','Graphic Elements & Color','Rules, fields, markers, and color organize information—but no single palette or shape vocabulary defines Bauhaus work.'))+
 lesson('graphic-elements','II · 2.4.1 · Graphic Elements','2.4.1','Graphic Elements','Ask what an element does before naming what it resembles.',`<div class="function-map"><div><i></i><b>Connect</b><span>bind related information</span></div><div><i></i><b>Group</b><span>create a shared region</span></div><div><i>03</i><b>Locate</b><span>mark sequence</span></div></div>`)+
 lesson('color-function','II · 2.4.2 · Color Function','2.4.2','Color Function','Before interpreting color symbolically, test its organizational work.',`<div class="color-table">${[['tone-1','Classify','repeat for one information type'],['tone-2','Emphasize','make a difference visible'],['tone-3','Connect','link separated parts']].map(x=>`<div><i class="${x[0]}"></i><b>${x[1]}</b><p>${x[2]}</p></div>`).join('')}</div>`)+
 lesson('restraint','II · 2.4.3 · Restraint','2.4.3','Restraint','The familiar red-yellow-blue shorthand is not a neutral summary of Bauhaus practice.',`<div class="critical-note">${badge('fact','Historical distinction · sourced')}<p>The Bauhaus-Archiv notes that basic shapes and colors in Bayer’s 1968 “50 Years of the Bauhaus” poster strongly influenced later public perception. It should not be projected backward as a rule for work made at the school. <button class="cite" data-pop="poster-legacy">2</button></p></div>`)}
function lesson(id,loc,code,title,lead,body){return frame(id,loc,`<header class="compact-head"><div><span>${code}</span><h2>${title}</h2></div><p class="lead">${lead}</p></header>${body}`)}
function promptBox(items){return `<article class="annotation"><h3>Reading prompt</h3><ol>${items.map(x=>`<li>${x}</li>`).join('')}</ol></article>`}

function objects(){return frame('microscope','III · Works Under the Microscope',head('III','Works Under the Microscope','Two sourced objects test how documentation, close looking, and transparent inference coexist.')+objectStudy('schmidt','1923','Joost Schmidt','Staatliches Bauhaus Ausstellung','1923','Lithograph, 66.7 × 47.3 cm. Printer: von Reineck & Klein, Weimar. The Museum of Modern Art, gift of Walter Gropius. Object 320.1957.','https://www.moma.org/collection/works/6235',['How does circular movement interact with the format?','Which alignments connect type and image?','Where does scale establish sequence?'])+objectStudy('bayer','architecture<br>light images','Herbert Bayer','Architektur Lichtbilder Vortrag Professor Hans Poelzig','1926','Letterpress, 48.6 × 65.1 cm. Printer: Bauhausdruck. The Museum of Modern Art, gift of Philip Johnson. Object 108.1968.','https://www.moma.org/collection/works/5101',['Map subject, speaker, and event hierarchy.','Test how a grid permits asymmetry.','Compare density across regions.']))}
function objectStudy(cls,mark,creator,title,year,meta,link,questions){return `<article class="object-study"><figure><div class="object-placeholder ${cls}"><span>Licensed reproduction required</span><strong>${mark}</strong><small>placeholder · not a reproduction</small></div><figcaption><b>${creator}</b><em>${title}</em>, ${year}. ${meta} <a href="${link}" target="_blank" rel="noreferrer">Object record ↗</a></figcaption></figure><div>${badge('object','Sourced object + our analysis')}<h3>Close-reading prompts</h3><ol>${questions.map(x=>`<li>${x}</li>`).join('')}</ol><p class="note">Metadata is documented by MoMA. The prompts are ours; visual claims require an authorized reproduction.</p></div></article>`}
function ending(){return frame('publication','IV · Bauhaus in Publication',head('IV','Bauhaus in Publication','A page belongs to a sequence, binding, production method, and reading situation.')+`<div class="publication-grid"><div class="page-sequence"><div></div><div></div><div></div></div><div class="annotation"><h3>Expand the unit of analysis</h3><p>Study covers, margins, contents, running matter, captions, image rhythm, and transitions.</p>${badge('demo','Original demonstration · not historical')}<p>Later research should pair these page studies with licensed, catalogued publications.</p><button class="term" data-pop="internal" data-internal="grid">See also: analytical grid →</button></div></div>`)+frame('after','V · After Bauhaus',head('V','After Bauhaus','Historical Bauhaus is not identical to the later visual idea of “Bauhaus.”')+`<div class="after-grid"><div>then<br><span>≠</span><br>now</div><div><p>This section will trace transmission, migration, revival, and simplification while keeping later influence visibly separate from work made at the school.</p><button class="action" data-home>Return to collection</button></div></div>`)}

const popovers={
 'source-archive':{title:'[1] Bauhaus.Typography',body:'The Bauhaus-Archiv describes typography at the school as varied: an early expressive-calligraphic phase was followed by work from figures including Moholy-Nagy, Bayer, and Schmidt that helped spread New Typography.',link:'https://www.bauhaus.de/forschen/publikationen/bauhaus-typography/'},
 'poster-legacy':{title:'[2] Poster collection and reception',body:'The Bauhaus-Archiv discusses Bayer’s 1968 exhibition poster and the role its basic forms and colors played in later perception of the Bauhaus legacy.',link:'https://www.bauhaus.de/en/discover/article/our-history-part-4-a-statement-with-a-message-the-poster-collection/'},
 reconstruction:{title:'Analytical reconstruction',body:'A structure inferred from visible evidence. It may reveal alignments and proportions, but is not proof of documented process. Exceptions should remain visible.'},
 internal:{title:'Internal reference',body:'The previous section is stored so Back returns to the precise topic you came from.'}
};
function searchPanel(){return `<aside class="search-panel" role="dialog" aria-modal="true"><button class="search-close" data-search>Close ×</button><label for="searchInput">Search the collection</label><input id="searchInput" autocomplete="off" placeholder="Try “alignment” or “caption”"><div id="results">${results('')}</div></aside>`}
function results(q){q=q.toLowerCase();const hits=outline.filter(x=>`${x.title} ${x.search}`.toLowerCase().includes(q));return hits.map(x=>`<button class="result" data-result="${x.id}"><small>Book I · ${x.roman||'Visual Language'}</small><strong>${x.title}</strong><span>${x.search}</span></button>`).join('')||'<p>No matching prototype content.</p>'}
function jump(id,store=true){if(store&&state.view==='book')sessionStorage.setItem('tvl-back',state.active);state.view='book';state.search=false;state.menu=false;render();const target=document.getElementById(id);if(target)window.scrollTo(0,target.offsetTop-96)}
function pop(el,key){document.querySelector('.popover')?.remove();const p=popovers[key],r=el.getBoundingClientRect(),n=document.createElement('div');n.className='popover';n.style.left=Math.min(innerWidth-392,Math.max(16,r.left))+'px';n.style.top=Math.min(innerHeight-240,Math.max(70,r.bottom+10))+'px';n.innerHTML=`<button class="close">×</button><h3>${p.title}</h3><p>${p.body}</p>${p.link?`<a href="${p.link}" target="_blank" rel="noreferrer">View source ↗</a>`:''}`;document.body.append(n);n.querySelector('.close').onclick=()=>n.remove()}
function bind(){document.querySelectorAll('[data-home]').forEach(x=>x.onclick=()=>{state.view='home';state.menu=false;render();scrollTo(0,0)});document.querySelectorAll('[data-open-book]').forEach(x=>{x.onclick=()=>jump('opening',false);x.onkeydown=e=>{if(['Enter',' '].includes(e.key))jump('opening',false)}});document.querySelectorAll('[data-resume]').forEach(x=>x.onclick=()=>jump(x.dataset.resume,false));document.querySelectorAll('[data-jump]').forEach(x=>x.onclick=()=>jump(x.dataset.jump));document.querySelectorAll('[data-search]').forEach(x=>x.onclick=()=>{state.search=!state.search;render();if(state.search)setTimeout(()=>document.querySelector('#searchInput')?.focus())});document.querySelector('[data-menu]')?.addEventListener('click',()=>{state.menu=!state.menu;render()});document.querySelector('[data-save]')?.addEventListener('click',()=>{let a=saved();a=a.includes('bauhaus')?a.filter(x=>x!=='bauhaus'):[...a,'bauhaus'];localStorage.setItem('tvl-saved',JSON.stringify(a));render()});document.querySelector('[data-back]')?.addEventListener('click',()=>jump(sessionStorage.getItem('tvl-back')||'opening',false));document.querySelector('[data-grid]')?.addEventListener('click',e=>{const d=document.querySelector('#diagram');d.classList.toggle('grid-on');e.currentTarget.textContent=d.classList.contains('grid-on')?'Hide analytical grid':'Show analytical grid'});document.querySelectorAll('[data-pop]').forEach(x=>x.onclick=()=>x.dataset.internal?jump(x.dataset.internal):pop(x,x.dataset.pop));document.querySelector('#searchInput')?.addEventListener('input',e=>{document.querySelector('#results').innerHTML=results(e.target.value);bindResults()});bindResults()}
function bindResults(){document.querySelectorAll('[data-result]').forEach(x=>x.onclick=()=>jump(x.dataset.result))}
let observer;function observe(){observer?.disconnect();observer=new IntersectionObserver(es=>{const hit=es.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!hit)return;state.active=hit.target.id;remember(state.active);document.querySelectorAll('[data-jump]').forEach(x=>x.classList.toggle('active',x.dataset.jump===state.active));const l=document.querySelector('#location');if(l)l.textContent=hit.target.dataset.loc},{rootMargin:'-12% 0px -68% 0px',threshold:[0,.1,.35]});document.querySelectorAll('.page-frame').forEach(x=>observer.observe(x))}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(state.search){state.search=false;render()}else document.querySelector('.popover')?.remove()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();state.search=true;render();setTimeout(()=>document.querySelector('#searchInput')?.focus())}});render();
